worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  _;

        # 托管 React 打包后的静态文件
        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }

        # 代理到 tStudio 后端 API 和 WebSocket
        location /api/ {
            # Kubernetes 中的 tStudio 后端服务地址
            resolver 169.254.25.10 10.233.0.3 valid=30s ipv6=off;
            set $backend_url http://ruoyi-tstudio.inspection-dev.svc.cluster.local:8000;
            
            # WebSocket 支持
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            proxy_pass $backend_url;
        }
        
        # 避免actuator暴露
        if ($uri ~ "/actuator") {
            return 403;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
